# Production docker-compose.yml
# This file is automatically created by GitHub Actions on the server
# It's included here as reference/documentation

version: "3.9"

services:
  strapi:
    image: ghcr.io/yourusername/awesomeapps.strapi:latest
    container_name: strapi
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=strapiDB
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - PORT=1337
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    labels:
      # Traefik automatic routing
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`strapi.meimberg.io`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=le"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"
    networks:
      - strapi
      - traefik
    depends_on:
      - strapiDB

  strapiDB:
    image: mysql:8.0
    container_name: strapiDB
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=strapi
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=strapi
      - MYSQL_TCP_PORT=3306
    command: --default-authentication-plugin=mysql_native_password --port=3306
    volumes:
      - strapi-data:/var/lib/mysql
    networks:
      - strapi

volumes:
  strapi-data:
  strapi-uploads:

networks:
  strapi:
    driver: bridge
  traefik:
    external: true

