# Production docker-compose.yml
# Used by GitHub Actions deployment workflow
# Variables are substituted using envsubst during deployment

version: "3.9"

services:
  ${PROJECT_NAME}:
    image: ${DOCKER_IMAGE}
    container_name: ${PROJECT_NAME}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${PROJECT_NAME}-uploads:/opt/app/public
      - /srv/backups/strapi:/opt/app/backup  # Backup mount
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=le"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=1337"
    networks:
      - ${PROJECT_NAME}
      - traefik
    depends_on:
      - ${PROJECT_NAME}-db

  ${PROJECT_NAME}-db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-db
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=strapi
      - MYSQL_ROOT_PASSWORD=\${DATABASE_PASSWORD}
      - MYSQL_PASSWORD=\${DATABASE_PASSWORD}
      - MYSQL_DATABASE=strapi
      - MYSQL_TCP_PORT=3306
    command: --default-authentication-plugin=mysql_native_password --port=3306
    volumes:
      - ${PROJECT_NAME}-data:/var/lib/mysql
    networks:
      - ${PROJECT_NAME}

volumes:
  ${PROJECT_NAME}-data:
  ${PROJECT_NAME}-uploads:

networks:
  ${PROJECT_NAME}:
    driver: bridge
  traefik:
    external: true

